export const GET_POPULAR_MOVIES_REQUEST = 'GET_POPULAR_MOVIES_REQUEST';
export const GET_POPULAR_MOVIES_SUCCESS = 'GET_POPULAR_MOVIES_SUCCESS';
export const GET_POPULAR_MOVIES_FAILURE = 'GET_POPULAR_MOVIES_FAILURE';

export const GET_GENRES_REQUEST = 'GET_GENRES_REQUEST';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';

export const GET_MOVIE_DETAILS_REQUEST = 'GET_MOVIE_DETAILS_REQUEST';
export const GET_MOVIE_DETAILS_SUCCESS = 'GET_MOVIE_DETAILS_SUCCESS';
export const GET_MOVIE_DETAILS_FAILURE = 'GET_MOVIE_DETAILS_FAILURE';

export const GET_MOVIE_RECOMMENDATIONS_REQUEST = 'GET_MOVIE_RECOMMENDATIONS_REQUEST';
export const GET_MOVIE_RECOMMENDATIONS_SUCCESS = 'GET_MOVIE_RECOMMENDATIONS_SUCCESS';
export const GET_MOVIE_RECOMMENDATIONS_FAILURE = 'GET_MOVIE_RECOMMENDATIONS_FAILURE';

export const GET_MOVIE_SEARCH_RESULTS_REQUEST = 'GET_MOVIE_SEARCH_RESULTS_REQUEST';
export const GET_MOVIE_SEARCH_RESULTS_SUCCESS = 'GET_MOVIE_SEARCH_RESULTS_SUCCESS';
export const GET_MOVIE_SEARCH_RESULTS_FAILURE = 'GET_MOVIE_SEARCH_RESULTS_FAILURE';
