name: Caching node_modules

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: true
      - name: Build
        run: yarn build
